name: Label workflow

# Controls when the action will run. tested
on:
  pull_request:
    types:
      - labeled
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - id: preview_label_check
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: adapters
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          allow_failure: true
      - if: steps.preview_label_check.outputs.label_check == 'success'
        run: echo deploy to ephemeral environment
